### ISSUE TITLE
Removed from Chrome Web Store 😟

### ISSUE THREAD

**Issue by JackNUMBER** [wayne5540/chrome-aerial#1]
Hi, the extension recently been removed from the chrome web store and is not available on if you had installed it on Chrome:

![image](https://user-images.githubusercontent.com/2306550/177787246-1d82cf02-3ab1-47fb-90db-ad18cd1bd74b.png)
"_This extension doesn't follow Chrome Web Store rules_"

Any way to fix and submit again the extension?

**Comment by wayne5540** [comment]
Oh Hi @JackNUMBER, I'm actually surprised that we have users for this chrome extension! Thanks for using it :)

Unfortunately I'm not able to keep maintaining this app, the reason it got removed is that I'm asking `tabs` permission but not using it. (that's the reason I got from email)
So to put it back on chrome store, we just need to remove the un-used permission I guess. (finger crossed)

**Comment by wayne5540** [comment]
I updated the permission and re-submit the app to chrome store, hopefully it'll go live again.
